//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD:FeatureInterface/Properties/Resources.Designer.cs
namespace FeatureInterface.Properties {
=======
namespace CSCI363_GeneralDisarrays_JonsWindow1.Properties {
>>>>>>> JonTestBranch:CSCI363_GeneralDisarrays_JonsWindow1/Properties/Resources.Designer.cs
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
<<<<<<< HEAD:FeatureInterface/Properties/Resources.Designer.cs
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeatureInterface.Properties.Resources", typeof(Resources).Assembly);
=======
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSCI363_GeneralDisarrays_JonsWindow1.Properties.Resources", typeof(Resources).Assembly);
>>>>>>> JonTestBranch:CSCI363_GeneralDisarrays_JonsWindow1/Properties/Resources.Designer.cs
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD:FeatureInterface/Properties/Resources.Designer.cs
        internal static System.Drawing.Bitmap Check_Engine_Light_PNG_Photo {
            get {
                object obj = ResourceManager.GetObject("Check-Engine-Light-PNG-Photo", resourceCulture);
=======
        internal static System.Drawing.Bitmap IMG_20170726_094506_12 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170726_094506_12", resourceCulture);
>>>>>>> JonTestBranch:CSCI363_GeneralDisarrays_JonsWindow1/Properties/Resources.Designer.cs
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD:FeatureInterface/Properties/Resources.Designer.cs
        internal static System.Drawing.Bitmap Geofencing {
            get {
                object obj = ResourceManager.GetObject("Geofencing", resourceCulture);
=======
        internal static System.Drawing.Bitmap IMG_20170727_094956_12 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170727_094956_12", resourceCulture);
>>>>>>> JonTestBranch:CSCI363_GeneralDisarrays_JonsWindow1/Properties/Resources.Designer.cs
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD:FeatureInterface/Properties/Resources.Designer.cs
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap startButton {
            get {
                object obj = ResourceManager.GetObject("startButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windshieldFluid {
            get {
                object obj = ResourceManager.GetObject("windshieldFluid", resourceCulture);
=======
        internal static System.Drawing.Bitmap IMG_20170811_094114_2 {
            get {
                object obj = ResourceManager.GetObject("IMG_20170811_094114_2", resourceCulture);
>>>>>>> JonTestBranch:CSCI363_GeneralDisarrays_JonsWindow1/Properties/Resources.Designer.cs
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
